#ddev-generated
services:
    web:
        extra_hosts:
        - "host.docker.internal:host-gateway"
        environment:
        - "VAR_DUMPER_FORMAT=server"
        - "VAR_DUMPER_SERVER=host.docker.internal:9912"
